server/bin/pkgstatic

diff --git a/keys/mfsbsdonly/etc/rc.d/jautopkg b/keys/mfsbsdonly/etc/rc.d/jautopkg
--- a/keys/mfsbsdonly/etc/rc.d/jautopkg
+++ b/keys/mfsbsdonly/etc/rc.d/jautopkg
@@ -16,34 +16,19 @@ stop_cmd=":"
 jautopkg_start()
 {
 	local trylocal="NO"
-	if [ -e /etc/pkg/FreeBSD.conf ]; then
-		/bin/mv /etc/pkg/FreeBSD.conf /etc/pkg.FreeBSD.conf.bkp
-	fi
-	if ! /sbin/mount | /usr/bin/grep "/var/cache/pkg" > /dev/null 2> /dev/null; then
-		/sbin/mount -t tmpfs tmpfs /var/cache
-	fi
-	if ! /sbin/mount | /usr/bin/grep "/var/db/pkg" > /dev/null 2> /dev/null; then
-		/sbin/mount -t tmpfs tmpfs /var/db/pkg
-	fi
-	if [ -x /usr/local/sbin/pkg-static ]; then
-		if /sbin/ifconfig | /usr/bin/grep status | /usr/bin/grep -v "no carrier" \
-		| /usr/bin/grep . > /dev/null 2> /dev/null ; then
+	if [ -x /server/bin/pkgstatic ]; then
+		if /sbin/ifconfig | /usr/bin/grep status | /usr/bin/grep " active" > /dev/null 2> /dev/null ; then
 			autopkg=`/bin/kenv -q autopkg`
-			test -e /usr/local/etc/pkg/repos/myrepo.conf \
-			&& REPOURL=$( /usr/bin/grep URL: /usr/local/etc/pkg/repos/myrepo.conf \
-			| /usr/bin/egrep -v '^\s*#' | /usr/bin/awk '{print $NF}' | /usr/bin/head -1 )
-			if /usr/bin/fetch -o /dev/null -T 3 "${REPOURL}/digests.txz" ; then
-				TRIMLIST="`echo $autopkg | /usr/bin/tr -d ' '`"
-				if [ -n "${TRIMLIST}" ]; then
-					echo -n "Installing packages remotely... "
-					for i in ${autopkg} ; do
-						/usr/local/sbin/pkg-static install -y $i > /dev/null 2> /dev/null || echo "ERROR: pkg install $i"
-					done
-					echo " done"
-				fi
-				if ! /usr/local/sbin/pkg-static info | /usr/bin/grep 'rsync' > /dev/null 2> /dev/null; then
-					local trylocal="YES"
-				fi
+			TRIMLIST="`echo $autopkg | /usr/bin/tr -d ' '`"
+			if [ -n "${TRIMLIST}" ]; then
+				echo -n "Installing packages remotely... "
+				for i in ${autopkg} ; do
+					/server/bin/pkgstatic install -y $i > /dev/null 2> /dev/null || echo "ERROR: pkg install $i"
+				done
+				echo " done"
+			fi
+			if ! /server/bin/pkgstatic info | /usr/bin/grep 'rsync' > /dev/null 2> /dev/null; then
+				local trylocal="YES"
 			fi
 		else
 			local trylocal="YES"
@@ -57,7 +42,7 @@ jautopkg_start()
 					LOOP=0;
 					echo -n '.'
 					for i in /packages/*.t?z ; do
-						/usr/local/sbin/pkg-static add $i 2>&1 | /usr/bin/grep 'already installed' > /dev/null 2> /dev/null || LOOP=1
+						/server/bin/pkgstatic add $i 2>&1 | /usr/bin/grep 'already installed' > /dev/null 2> /dev/null || LOOP=1
 					done
 				done
 				echo " done"
