loop through autopkg

diff --git a/keys/mfsbsdonly/etc/rc.d/jautopkg b/keys/mfsbsdonly/etc/rc.d/jautopkg
--- a/keys/mfsbsdonly/etc/rc.d/jautopkg
+++ b/keys/mfsbsdonly/etc/rc.d/jautopkg
@@ -29,7 +29,9 @@ jautopkg_start()
 	if /usr/bin/fetch -o /dev/null -T 10 "${REPOURL}/digests.txz" ; then
 		TRIMLIST="`echo $autopkg | /usr/bin/tr -d ' '`"
 		if [ -n "${TRIMLIST}" ]; then
-			/usr/local/sbin/pkg-static install -y ${autopkg} || echo "Error: pkg install $i"
+			for i in ${autopkg} ; do
+				/usr/local/sbin/pkg-static install -y $i || echo "ERROR: pkg install $i"
+			done
 		fi
 	fi
 	if ! /usr/local/sbin/pkg info | /usr/bin/grep 'rsync' > /dev/null 2> /dev/null; then
