fix some startup scripts

diff --git a/keys/mfsbsdonly/etc/rc.d/jautopkg b/keys/mfsbsdonly/etc/rc.d/jautopkg
--- a/keys/mfsbsdonly/etc/rc.d/jautopkg
+++ b/keys/mfsbsdonly/etc/rc.d/jautopkg
@@ -25,39 +25,41 @@ jautopkg_start()
 	if ! /sbin/mount | /usr/bin/grep "/var/db/pkg" > /dev/null 2> /dev/null; then
 		/sbin/mount -t tmpfs tmpfs /var/db/pkg
 	fi
-	autopkg=`/bin/kenv -q autopkg`
-	REPOURL=$( /usr/bin/grep URL: /usr/local/etc/pkg/repos/myrepo.conf | /usr/bin/egrep -v '^\s*#' | /usr/bin/awk '{print $NF}' | /usr/bin/head -1 )
-	if /usr/bin/fetch -o /dev/null -T 10 "${REPOURL}/digests.txz" ; then
-		TRIMLIST="`echo $autopkg | /usr/bin/tr -d ' '`"
-		if [ -n "${TRIMLIST}" ]; then
-			echo -n "Installing packages remotely... "
-			if /sbin/ifconfig | /usr/bin/grep status | /usr/bin/grep -v "no carrier" \
-			| /usr/bin/grep . > /dev/null 2> /dev/null ; then
-				for i in ${autopkg} ; do
-					/usr/local/sbin/pkg-static install -y $i > /dev/null 2> /dev/null || echo "ERROR: pkg install $i"
-				done
+	if [ -x /usr/local/sbin/pkg-static ]; then
+		autopkg=`/bin/kenv -q autopkg`
+		REPOURL=$( /usr/bin/grep URL: /usr/local/etc/pkg/repos/myrepo.conf | /usr/bin/egrep -v '^\s*#' | /usr/bin/awk '{print $NF}' | /usr/bin/head -1 )
+		if /usr/bin/fetch -o /dev/null -T 10 "${REPOURL}/digests.txz" ; then
+			TRIMLIST="`echo $autopkg | /usr/bin/tr -d ' '`"
+			if [ -n "${TRIMLIST}" ]; then
+				echo -n "Installing packages remotely... "
+				if /sbin/ifconfig | /usr/bin/grep status | /usr/bin/grep -v "no carrier" \
+				| /usr/bin/grep . > /dev/null 2> /dev/null ; then
+					for i in ${autopkg} ; do
+						/usr/local/sbin/pkg-static install -y $i > /dev/null 2> /dev/null || echo "ERROR: pkg install $i"
+					done
+				fi
+				echo " done"
+				if ! /usr/local/sbin/pkg-static info | /usr/bin/grep 'rsync' > /dev/null 2> /dev/null; then
+					local trylocal="YES"
+				fi
 			fi
-			echo " done"
-			if ! /usr/local/sbin/pkg-static info | /usr/bin/grep 'rsync' > /dev/null 2> /dev/null; then
-				local trylocal="YES"
-			fi
+		else
+			local trylocal="YES"
 		fi
-	else
-		local trylocal="YES"
-	fi
-	if [ "x$trylocal" = "xYES" ]; then
-		PACKAGES=`/bin/ls -1 /packages/*.t?z 2>/dev/null`
-		if /bin/test -n "$PACKAGES"; then
-			echo -n "Installing from /packages"
-			LOOP=1
-			while [ $LOOP -eq 1 ]; do
-				LOOP=0;
-				echo -n '.'
-				for i in /packages/*.t?z ; do
-					/usr/local/sbin/pkg-static add $i 2>&1 | /usr/bin/grep 'already installed' > /dev/null 2> /dev/null || LOOP=1
+		if [ "x$trylocal" = "xYES" ]; then
+			PACKAGES=`/bin/ls -1 /packages/*.t?z 2>/dev/null`
+			if /bin/test -n "$PACKAGES"; then
+				echo -n "Installing from /packages"
+				LOOP=1
+				while [ $LOOP -eq 1 ]; do
+					LOOP=0;
+					echo -n '.'
+					for i in /packages/*.t?z ; do
+						/usr/local/sbin/pkg-static add $i 2>&1 | /usr/bin/grep 'already installed' > /dev/null 2> /dev/null || LOOP=1
+					done
 				done
-			done
-			echo " done"
+				echo " done"
+			fi
 		fi
 	fi
 	if /usr/sbin/service -e | /usr/bin/grep usr/local > /dev/null 2> /dev/null; then
