cleanup

diff --git a/keys/all/server/bin/jrolebootstrap b/keys/all/server/bin/jrolebootstrap
--- a/keys/all/server/bin/jrolebootstrap
+++ b/keys/all/server/bin/jrolebootstrap
@@ -23,8 +23,8 @@ IPCOUNT=$( echo "${PUBLICIP}" | /usr/bin/cut -d. -f4 )
 LOCALIPCOUNT=$( /usr/local/bin/ezjail-admin list |\
 	/usr/bin/grep -v "JID.*IP.*Hostname.*Directory" | /usr/bin/grep -v "\-\-\-" |\
 	/usr/bin/wc -l )
-if [ -e /server/csv/csv ]; then
-	CSV=$( /bin/cat /server/csv/csv | /usr/bin/tr -d '\n' )
+if [ -e /server/csv/id ]; then
+	CSV=$( /bin/cat /server/csv/id | /usr/bin/tr -d '\n' )
 else
 	CSV=''
 fi
@@ -125,14 +125,14 @@ jrolebgstart () {
 		| /usr/bin/grep "pxe" | /usr/bin/awk '{print $4}' )
 
 ############################################
-	elif [ "$1" = "pkgng" \
-	-o "$1" = "freebsd-dist" \
-	-o "$1" = "littlechef" ]; then
+	elif [ "$1" = "pkgng" -o "$1" = "freebsd-dist" -o "$1" = "littlechef" ]; then
 
 		/usr/local/bin/ezjail-admin console -e "/server/bin/start$1" "${2}"
 
 ############################################
-	elif [ "$1" = "blank" ]; then echo
+	elif [ "$1" = "blank" ]; then
+
+		echo
 
 ############################################
 	elif [ "$1" = "release" ]; then
@@ -150,7 +150,9 @@ jrolebgstart () {
 
 ############################################
 
-	else echo "Not implemented: jrolebgstart ${1} ${2}" ; exit 1
+	else
+
+		echo "Not implemented: jrolebgstart ${1} ${2}" ; exit 1
 
 	fi
 }
@@ -462,7 +464,7 @@ EOF
 jrolecreate (){
 
 	[ $# -lt 3 ] && echo "Usage: `basename $0` role jailname 'nic|ip'" && exit 1
-	
+
 	testforx /usr/local/bin/ezjail-admin
 
 	local safejailname=$( echo -n "$2" | /usr/bin/tr -c '[:alnum:]' _ )
@@ -475,7 +477,7 @@ jrolecreate (){
 
 ############################################
 	if [ "$1" = "dhcpd" ]; then
-		
+
 		/usr/bin/egrep "jrolecreate" "/usr/local/etc/ezjail/${safejailname}" \
 		> /dev/null 2> /dev/null \
 		|| /bin/cat >> "/usr/local/etc/ezjail/${safejailname}" <<EOF
@@ -487,11 +489,7 @@ export jail_${safejailname}_parameters="allow.raw_sockets=1"
 EOF
 
 ############################################
-	elif [ "$1" = "pxe" \
-	-o "$1" = "pkgng" \
-	-o "$1" = "freebsd-dist" \
-	-o "$1" = "littlechef" \
-	-o "$1" = "blank" ]; then
+	elif [ "$1" = "pxe" -o "$1" = "pkgng" -o "$1" = "freebsd-dist" -o "$1" = "littlechef" -o "$1" = "blank" ]; then
 
 		/usr/bin/egrep "jrolecreate" "/usr/local/etc/ezjail/${safejailname}" \
 		> /dev/null 2> /dev/null \
@@ -527,7 +525,9 @@ export jail_${safejailname}_parameters="allow.chflags allow.mount allow.mount.de
 EOF
 
 ############################################
-	else echo "Not implemented: jrolecreate $1" ; exit 1
+	else
+
+		echo "Not implemented: jrolecreate $1" ; exit 1
 
 	fi
 
@@ -611,7 +611,6 @@ jrolesetupflavours (){
 		"/server/pkg/key.pub" \
 		"${MNT}/server/pkg/key.pub"
 
-
 		for fil in /server/bin/* ; do
 
 			/usr/bin/install    -m 700 \
@@ -644,14 +643,15 @@ jrolesetupflavours (){
 
 		done
 
-
 		/bin/cat /root/.ssh/authorized_keys > "${MNT}/root/.ssh/authorized_keys"
 
 		/bin/chmod 600 "${MNT}/root/.ssh/authorized_keys"
 
 #####		SPECIFIC	#####
 
-		if [ "$1" = "dhcpd" ]; then jrolesetupservice "dhcpd" "${MNT}"
+		if [ "$1" = "dhcpd" ]; then
+
+			jrolesetupservice "dhcpd" "${MNT}"
 
 		elif [ "$1" = "pxe" ]; then
 
@@ -668,14 +668,13 @@ jrolesetupflavours (){
 			jrolesetupservice "nginx" "${MNT}"
 			jrolesetupservice "freebsd-dist" "${MNT}"
 
-		elif [ "$1" = "release" \
-		-o "$1" = "mfsbsd" \
-		-o "$1" = "blank" \
-		-o "$1" = "littlechef" ]; then
+		elif [ "$1" = "release" -o "$1" = "mfsbsd" -o "$1" = "blank" -o "$1" = "littlechef" ]; then
 
 			jrolesetupservice "$1" "${MNT}"
 
-		else echo "Not implemented: jrolesetupflavours $1" ; exit 1
+		else
+
+			echo "Not implemented: jrolesetupflavours $1" ; exit 1
 
 		fi
 
@@ -798,13 +797,17 @@ jrolesetupservice (){
 
 		done
 
-	elif [ "$1" = "mfsbsd" \
-	-o "$1" = "blank" \
-	-o "$1" = "littlechef" ]; then echo
+	elif [ "$1" = "mfsbsd" -o "$1" = "blank" -o "$1" = "littlechef" ]; then
 
-	elif [ "$1" = "release" ]; then jrolelinksrc "$2"
+		echo
 
-	else echo "Not implemented: jrolesetupservice $1" ; exit 1
+	elif [ "$1" = "release" ]; then
+
+		jrolelinksrc "$2"
+
+	else
+
+		echo "Not implemented: jrolesetupservice $1" ; exit 1
 
 	fi
 
@@ -816,15 +819,14 @@ jrolesetupservice (){
 jrolejailcreate (){
 
 	[ $# -lt 3 ] && echo "Usage: `basename $0` role jailname 'nic|ip'" && exit 1
-	
+
 	testforx /usr/local/bin/ezjail-admin
 
 	local ip=$( echo "$3" | /usr/bin/awk -F'|' '{print $2}' )
 
 	local safejailname=$( echo -n "$2" | /usr/bin/tr -c '[:alnum:]' _ )
 
-	if ! /usr/local/bin/ezjail-admin list | /usr/bin/grep "${2}" \
-	> /dev/null 2> /dev/null ; then
+	if ! /usr/local/bin/ezjail-admin list | /usr/bin/grep "${2}" > /dev/null 2> /dev/null ; then
 
 		/usr/local/bin/ezjail-admin create -f "${1}" "${2}" "${3}"
 
@@ -960,8 +962,7 @@ jrolesetupbasejail () {
 		else
 
 			# Test 10.7.7.4
-			if /usr/bin/fetch -T 10 \
-			-o /dev/null "http://${PRODIP}.4/freebsd-dist/10.0-RELEASE/base.txz" ; then
+			if /usr/bin/fetch -T 10 -o /dev/null "http://${PRODIP}.4/freebsd-dist/10.0-RELEASE/base.txz" ; then
 
 				# no -s for source since we have a svn in data/distro/releng10
 
@@ -986,7 +987,8 @@ jrolesetupbasejail () {
 
 	# If basejail still missing
 	if [ ! -d /usr/jails/basejail ]; then
-	echo "Error: base jail does not exist." ; exit 1 ; fi
+		echo "Error: base jail does not exist." ; exit 1
+	fi
 
 	# Reset some permissions for basejail
 	/bin/chmod 755 /usr/jails/basejail
@@ -1080,8 +1082,7 @@ jrolenatcreate (){
 	jrolenat     "${1}" "${2}" "${3}"
 
 	# If jail doesn't exist
-	if ! /usr/local/bin/ezjail-admin list | /usr/bin/grep "${2}" \
-	> /dev/null 2> /dev/null ; then
+	if ! /usr/local/bin/ezjail-admin list | /usr/bin/grep "${2}" > /dev/null 2> /dev/null ; then
 
 		jrolecreate  "${1}" "${2}" "${3}"
 
@@ -1140,7 +1141,9 @@ jrolesendjail () {
 	local REMOTE_CONNECTION="/usr/bin/ssh -p ${REMOTE_PORT} ${REMOTE_HOST}"
 
 	# Catch unknown host key
-	if ! ${REMOTE_CONNECTION} echo ; then exit 1 ; fi
+	if ! ${REMOTE_CONNECTION} echo ; then
+		exit 1
+	fi
 
 	if /sbin/zfs list "data/ezjail/${1}" ; then
 
@@ -1213,7 +1216,9 @@ jrolesenddata () {
 	local REMOTE_CONNECTION="/usr/bin/ssh -p ${REMOTE_PORT} ${REMOTE_HOST}"
 
 	# Catch unknown host key
-	if ! ${REMOTE_CONNECTION} echo ; then exit 1 ; fi
+	if ! ${REMOTE_CONNECTION} echo ; then
+		exit 1
+	fi
 
 	if [ "$1" = "poudriere" ]; then
 
@@ -1381,7 +1386,6 @@ jrolemfsbsdjails () {
 
 }
 
-
 # ---------------------------------------------------------
 
 # Destroy flavour
@@ -1447,6 +1451,16 @@ jrolerecover () {
 	[ $# -lt 1 ] && echo "Usage: `basename $0` dhcpd|pxe" && exit 1
 
 	testforx /usr/local/bin/ezjail-admin
+
+	if /bin/ls -1 /bootdir/*.csv > /dev/null 2> /dev/null ; then
+
+		for i in $( /bin/ls -1 /bootdir/*.csv ); do
+
+			/bin/cp -av "${i}" /server/csv/dhcpd/ || exit 1
+
+		done
+
+	fi
 
 	# Create lan control jails
 	if [ "xdhcp" = "x${1}" -o "xdhcpd" = "x${1}" ]; then
@@ -1581,7 +1595,7 @@ jrolelinkmedia () {
 	# Restore pkgng too
 	local releasedir=$( /usr/bin/find "/packages" -name 'rsync*txz' \
 	| /usr/bin/head -1 )
-	
+
 	local distdir=$( /usr/bin/find /usr/jails/pkgng*/server/www -name "pkgng" \
 	| /usr/bin/head -1 )
 
@@ -1658,9 +1672,7 @@ jrolelinksrc () {
 
 	else
 
-		if ! /usr/bin/egrep 'sm_close_on_exec\(lowest' \
-		"${BASEJAIL}/usr/src/contrib/sendmail/src/conf.c" \
-		> /dev/null 2> /dev/null ; then
+		if ! /usr/bin/egrep 'sm_close_on_exec\(lowest' "${BASEJAIL}/usr/src/contrib/sendmail/src/conf.c" > /dev/null 2> /dev/null ; then
 
 			#/server/bin/aslr-patch
 			/usr/bin/patch -Np1 -d "${BASEJAIL}/usr/src" \
@@ -1835,7 +1847,7 @@ jrolelinkpkgng () {
 #		cd "${distdir}/" ; /usr/local/sbin/pkg-static repo ./ ; cd -
 
 	fi
-	
+
 	if [ "x" != "x${distdir}" ]; then
 
 		# Set permissions so nginx can serve
@@ -1866,8 +1878,7 @@ jroleproductionip () {
 
 	local newip="${PRODIP}.${oldip##*.}"
 
-	if echo "$oldip" | /usr/bin/grep "$LOCALIP" \
-	> /dev/null 2> /dev/null ; then
+	if echo "$oldip" | /usr/bin/grep "$LOCALIP" > /dev/null 2> /dev/null ; then
 
 		/bin/cat >> "/usr/local/etc/ezjail/${safejailname}" <<EOF
 export jail_${safejailname}_ip="${LOCALNIC}|${newip}"
@@ -1891,8 +1902,9 @@ testforx (){
 
 	[ $# -lt 1 ] && echo "Usage: `basename $0` file" && exit 1
 
-	test -x "$1" \
-	|| ( echo "Error: $1 not found"; exit 1 )
+	if [ ! -x "$1" ]; then
+		echo "Error: $1 not found or executable"; exit 1
+	fi
 
 }
 
@@ -1925,7 +1937,7 @@ getremotehost (){
 		echo "${1}"
 
 	fi
-	
+
 }
 # ---------------------------------------------------------
 
@@ -1943,7 +1955,7 @@ getremoteport (){
 		echo 22
 
 	fi
-	
+
 }
 
 # ---------------------------------------------------------
@@ -1981,7 +1993,6 @@ directory to use the functionality. If this is your first run, some scripts have
 been created in /server/bin for you." && { make_auto_links ; exit 1 ; }
 
 fi
-
 
 # Delete the tmpfile
 if [ -e "${TMPFILE}" ]; then
diff --git a/keys/all/server/bin/mfsbsd-upgrade b/keys/all/server/bin/mfsbsd-upgrade
--- a/keys/all/server/bin/mfsbsd-upgrade
+++ b/keys/all/server/bin/mfsbsd-upgrade
@@ -12,6 +12,8 @@ usage() {
 	echo "Usage: $0 [-h] -t|-T dist_url [-m mount_point] [-p zfs_pool_name] [-f zfs_fs_name]"
 }
 
+MFSBSD=1
+
 help() {
 	echo; echo "Upgrade FreeBSD's mfsroot.gz by fetching a compressed archive"
 	echo; echo "Required flags:"
@@ -28,137 +30,138 @@ help() {
 }
 
 if [ $# -gt 0 ]; then
-while getopts t:T:p:f:m:h o; do
-	case "$o" in
-		t) ARCHIVE="${OPTARG}" ;;
-		T) FETCH="${OPTARG}"; ARCHIVE="$FETCH" ;;
-		p) POOL="${OPTARG}" ;;
-		f) RFS="${OPTARG}" ;;
-		m) MNT="${OPTARG}" ;;
-		h) help; exit 1;;
-		[?]) usage; exit 1;;
-	esac
-done
+
+	while getopts t:T:p:f:m:h o; do
+		case "$o" in
+			t) ARCHIVE="${OPTARG}" ;;
+			T) FETCH="${OPTARG}"; ARCHIVE="$FETCH" ;;
+			p) POOL="${OPTARG}" ;;
+			f) RFS="${OPTARG}" ;;
+			m) MNT="${OPTARG}" ;;
+			h) help; exit 1 ;;
+			[?]) usage; exit 1 ;;
+		esac
+	done
+
 fi
 
-MFSBSD=1
-
 if [ -z "$FETCH" ]; then
+
 	FETCH="http://${server}:${port}/mfsbsd/${RELEASE}-${ARCH}/NOX-${RELEASE}-${ARCH}.tar"
 	ARCHIVE="$FETCH"
+
 fi
 
 if [ -z "$ARCHIVE" ]; then
-	usage
-	exit 1
+	usage ; exit 1
 fi
 
-if [ -z "$POOL" ]; then
-	POOL=autoboot
+test -z "$POOL" && POOL=autoboot
+
+test -z "$RFS" && RFS=bootdir
+
+test -z "$MNT" && MNT=/bootdir
+
+if ! /sbin/zpool list "$POOL" > /dev/null 2> /dev/null ; then
+	echo "Error: ZFS pool $POOL doesn't exists" ; exit 1
 fi
 
-if [ -z "$RFS" ]; then
-	RFS=bootdir
-fi
-
-if ! /sbin/zpool list $POOL > /dev/null 2> /dev/null; then
-	echo "Error: ZFS pool $POOL doesn't exists"
-	exit 1
-fi
-
-if ! /sbin/zfs list -o mounted,mountpoint $POOL/$RFS | /usr/bin/grep "$MNT" | /usr/bin/grep "yes" ; then
-	echo "Error: ZFS FS $POOL/$RFS not mounted"
-	exit 1
+if ! /sbin/zfs list -o mounted,mountpoint "$POOL/$RFS" | /usr/bin/grep "$MNT" | /usr/bin/grep "yes" > /dev/null 2> /dev/null ; then
+	echo "Error: ZFS FS $POOL/$RFS not mounted" ; exit 1
 fi
 
 if [ -z "${URL}" ]; then
+
 	if [ -n "${FETCH}" ]; then
+
 		echo "Fetching ... ${FETCH}"
-		if ! /usr/bin/fetch -o "/tmp/${FETCH##*/}" "${FETCH}"; then
-			echo "Error fetching ${FETCH}"
-			exit 1
+
+		if ! /usr/bin/fetch -o "/tmp/${FETCH##*/}" "${FETCH}" ; then
+			echo "Error fetching ${FETCH}" ; exit 1
 		fi
+
 		ARCHIVE="/tmp/${FETCH##*/}"
-		ARCHSIZE="`/bin/ls -l ${ARCHIVE} | /usr/bin/awk '{print $5}'`"
-		if [ $ARCHSIZE -lt 10000000 ]; then #10 MB
-			echo "Archive too small, fetch probably failed."
-			exit 1
+
+		ARCHSIZE=$( /bin/ls -l "${ARCHIVE}" | /usr/bin/awk '{print $5}' )
+
+		if [ $ARCHSIZE -lt 10000000 ]; then
+			echo "Archive too small, fetch probably failed." ; exit 1
 		fi
+
 	fi
-	if ! [ -f "${ARCHIVE}" ]; then
-		echo "Error: file $ARCHIVE does not exist"
-		exit 1
-	else
-		EXTRACT_FILES=${ARCHIVE}
+
+	if [ -f "${ARCHIVE}" ]; then
+		echo "Error: file $ARCHIVE does not exist" ; exit 1
 	fi
+
+	EXTRACT_FILES="${ARCHIVE}"
+
 fi
 
-if [ -z "$MNT" ]; then
-	MNT=/bootdir
+if [ ! -d "${MNT}" ]; then
+	echo "Error: $MNT is not a directory" ; exit 1
 fi
-
-if ! [ -d "${MNT}" ]; then
-	echo "Error: $MNT is not a directory"
-	exit 1
-fi
-
 
 TIMESTAMP=$( /bin/date '+%Y%m%dT%H%M%S%Z' )
+
 echo -n "Snapshotting autoboot/bootdir@upgrade-${TIMESTAMP} ..."
-if ! /sbin/zfs snapshot autoboot/bootdir@upgrade-${TIMESTAMP} > /dev/null 2> /dev/null; then
-	echo " error"
-	exit 1
+
+if ! /sbin/zfs snapshot "autoboot/bootdir@upgrade-${TIMESTAMP}" > /dev/null 2> /dev/null ; then
+	echo " error" ; exit 1
 fi
+
 echo " done"
 
-	/bin/mv ${MNT}/boot/loader.conf ${MNT}/boot/loader.conf.bkp
+/bin/mv "${MNT}/boot/loader.conf" "${MNT}/boot/loader.conf.bkp"
 
-	echo -n "Extracting FreeBSD distribution ..."
-	for file in ${EXTRACT_FILES}; do
-		if [ "$MFSBSD" = "1" ]; then
-			if ! /usr/bin/tar -C /bootdir --exclude=${RELEASE}-${ARCH} -x -f ${file} > /dev/null 2> /dev/null; then
-				echo " error"
-				exit 1
-			fi
-			if ! /usr/bin/tar -C /var/backups --include=${RELEASE}-${ARCH} -x -f ${file} > /dev/null 2> /dev/null; then
-				echo " error"
-				exit 1
-			fi
-			/bin/mv ${file} /var/backups/
-		else
-			exit 1
-		fi
-	done
-	echo " done"
+echo -n "Extracting FreeBSD distribution ..."
 
-	# Adjust configuration files
+for file in ${EXTRACT_FILES}; do
 
-	echo -n "Writing /boot/loader.conf..."
-	/usr/sbin/sysrc -f ${MNT}/boot/loader.conf aesni_load="YES"
-	/usr/sbin/sysrc -f ${MNT}/boot/loader.conf ahci_load="YES"
-	/usr/sbin/sysrc -f ${MNT}/boot/loader.conf geom_label_load="YES"
-	/usr/sbin/sysrc -f ${MNT}/boot/loader.conf geom_mirror_load="YES"
-	/usr/sbin/sysrc -f ${MNT}/boot/loader.conf kern.cam.boot_delay="10000"
-	/usr/sbin/sysrc -f ${MNT}/boot/loader.conf nullfs_load="YES"
-	/usr/sbin/sysrc -f ${MNT}/boot/loader.conf zfs_load="YES"
-	/usr/sbin/sysrc -f ${MNT}/boot/loader.conf geom_eli_load="YES"
-	/usr/sbin/sysrc -f ${MNT}/boot/loader.conf vfs.root.mountfrom="zfs:autoboot/bootdir"
-	/usr/bin/grep "^geli_label_" ${MNT}/boot/loader.conf.bkp >> ${MNT}/boot/loader.conf
-	/usr/bin/grep "^automount" ${MNT}/boot/loader.conf.bkp >> ${MNT}/boot/loader.conf
-	/usr/bin/grep "^autowifi" ${MNT}/boot/loader.conf.bkp >> ${MNT}/boot/loader.conf
-	/usr/bin/grep "^autogui" ${MNT}/boot/loader.conf.bkp >> ${MNT}/boot/loader.conf
-	echo " done"
-
-	echo ""
-	echo "Upgrade complete."
-	echo ""
-	echo "! ! ! ! ! ! ! ! ! !"
-	echo "! REBOOT REQUIRED !"
-	echo "! ! ! ! ! ! ! ! ! !"
-
-	if [ -e "/server/bin/zfscustom" ]; then
-		if [ -x /server/bin/zfscustom ]; then
-			MFSBSD=${MFSBSD} UPGRADE=1 /server/bin/zfscustom
-		fi
+	if [ "$MFSBSD" != "1" ]; then
+		echo "Not mfsbsd, aborting" ; exit 1
 	fi
 
+	if ! /usr/bin/tar -C /bootdir --exclude="${RELEASE}-${ARCH}" -x -f "${file}" > /dev/null 2> /dev/null ; then
+		echo " error" ; exit 1
+	fi
+
+	if ! /usr/bin/tar -C /var/backups --include="${RELEASE}-${ARCH}" -x -f "${file}" > /dev/null 2> /dev/null ; then
+		echo " error" ; exit 1
+	fi
+
+	/bin/mv "${file}" /var/backups/
+
+done
+
+echo " done"
+
+# Adjust configuration files
+
+echo -n "Writing /boot/loader.conf..."
+/usr/sbin/sysrc -f "${MNT}/boot/loader.conf" aesni_load="YES"
+/usr/sbin/sysrc -f "${MNT}/boot/loader.conf" ahci_load="YES"
+/usr/sbin/sysrc -f "${MNT}/boot/loader.conf" geom_label_load="YES"
+/usr/sbin/sysrc -f "${MNT}/boot/loader.conf" geom_mirror_load="YES"
+/usr/sbin/sysrc -f "${MNT}/boot/loader.conf" kern.cam.boot_delay="10000"
+/usr/sbin/sysrc -f "${MNT}/boot/loader.conf" nullfs_load="YES"
+/usr/sbin/sysrc -f "${MNT}/boot/loader.conf" zfs_load="YES"
+/usr/sbin/sysrc -f "${MNT}/boot/loader.conf" geom_eli_load="YES"
+/usr/sbin/sysrc -f "${MNT}/boot/loader.conf" vfs.root.mountfrom="zfs:autoboot/bootdir"
+/usr/bin/grep "^geli_label_" "${MNT}/boot/loader.conf.bkp" >> "${MNT}/boot/loader.conf"
+/usr/bin/grep "^automount" "${MNT}/boot/loader.conf.bkp" >> "${MNT}/boot/loader.conf"
+/usr/bin/grep "^autowifi" "${MNT}/boot/loader.conf.bkp" >> "${MNT}/boot/loader.conf"
+/usr/bin/grep "^autogui" "${MNT}/boot/loader.conf.bkp" >> "${MNT}/boot/loader.conf"
+echo " done"
+
+/bin/cat <<EOF
+
+Upgrade complete.
+
+! ! ! ! ! ! ! ! ! !
+! REBOOT REQUIRED !
+! ! ! ! ! ! ! ! ! !
+
+EOF
+
+test -x /server/bin/zfscustom && MFSBSD="${MFSBSD}" UPGRADE=1 /server/bin/zfscustom
diff --git a/keys/all/server/bin/startezjail b/keys/all/server/bin/startezjail
--- a/keys/all/server/bin/startezjail
+++ b/keys/all/server/bin/startezjail
@@ -6,11 +6,10 @@
 test -e /usr/local/bin/ezjail-admin \
 || /usr/local/sbin/pkg-static install -y ezjail
 
-
 # Test for net-ipreal as we use it below
-test -x /server/bin/net-ipreal \
-|| ( echo "Error: /server/bin/net-ipreal not found"; exit 1 )
-
+if [ ! -x /server/bin/net-ipreal ] ; then
+	echo "Error: /server/bin/net-ipreal not found"; exit 1
+fi
 
 # Add ListenAddress to ssh
 /bin/chflags noschg /etc/ssh/sshd_config
@@ -27,11 +26,9 @@ EOF
 done
 /bin/chflags schg /etc/ssh/sshd_config
 
-
 # If rc.d/sshd exists, onereload it
 test -x /etc/rc.d/sshd \
 && /etc/rc.d/sshd onereload 2> /dev/null
-
 
 # If ezjail-admin exists, modify it to look for fstab in /usr/local/etc/ezjail
 test -e /usr/local/bin/ezjail-admin \
@@ -39,20 +36,17 @@ test -e /usr/local/bin/ezjail-admin \
 's#etc/fstab\.#usr/local/etc/ezjail/fstab.#' \
 /usr/local/bin/ezjail-admin
 
-
 # If ezjail-admin exists, modify it to ignore fstab, ezjail.conf, and sig as jails
 test -e /usr/local/bin/ezjail-admin \
 && /usr/bin/sed -i '' \
 's#ls -A | xargs#ls -A | egrep -v "(fstab\.|ezjail\.conf|\.sig$)" | xargs#' \
 /usr/local/bin/ezjail-admin
 
-
 # If rc.d/ezjail exists, modify it to ignore fstab, ezjail.conf, and sig as jails
 test -e /usr/local/etc/rc.d/ezjail \
 && /usr/bin/sed -i '' \
 's#ls | xargs rcorder#ls | egrep -v "(fstab\.|ezjail\.conf|\.sig$)" | xargs#' \
 /usr/local/etc/rc.d/ezjail
-
 
 # If ezjail.conf is not configured, do so now
 /usr/bin/grep \
@@ -65,12 +59,8 @@ ezjail_use_zfs_for_jails="YES"
 ezjail_jailzfs="data/ezjail"
 EOF
 
-
 # If rc.d/ezjail exists, onestart it
-test -x /usr/local/etc/rc.d/ezjail \
-&& /usr/local/etc/rc.d/ezjail onestart
-
+test -x /usr/local/etc/rc.d/ezjail && /usr/local/etc/rc.d/ezjail onestart
 
 # If startucarp exists, run it
-test -x /server/bin/startucarp \
-&& /server/bin/startucarp
+test -x /server/bin/startucarp && /server/bin/startucarp
diff --git a/keys/all/server/bin/zfsdatapartition b/keys/all/server/bin/zfsdatapartition
--- a/keys/all/server/bin/zfsdatapartition
+++ b/keys/all/server/bin/zfsdatapartition
@@ -1,8 +1,8 @@
 #!/bin/sh
 # Copyright (c) 2014 John Ko
-
-RESTOREMASK=`umask`
-
+RESTOREMASK=$( umask )
+BOOTDIR=/bootdir
+/bin/df -H / | /usr/bin/grep '/dev/md[0-9]' > /dev/null 2> /dev/null && MFSBSD=1
 # bsdconfig has a neat way of defining zfs datasets, let's build on that
 debug=0
 DEBUG_SELF_INITIALIZE=0
@@ -13,42 +13,30 @@ f_include $BSDCFG_SHARE/device.subr > /dev/null 2> /dev/null
 f_include $BSDCFG_SHARE/dialog.subr > /dev/null 2> /dev/null
 f_include $BSDCFG_SHARE/password/password.subr > /dev/null 2> /dev/null
 f_include $BSDCFG_SHARE/variable.subr > /dev/null 2> /dev/null
-
-#FS_LIST="${FS_REG} ${FS_NOX}"
 ZFSBOOT_DATASETS="
 	# DATASET	OPTIONS (comma or space separated; or both)
-
 	# Boot Environment [BE] root and default boot dataset
 	#/$ZFSBOOT_BEROOT_NAME				mountpoint=none
 	#/$ZFSBOOT_BEROOT_NAME/$ZFSBOOT_BOOTFS_NAME	mountpoint=/
-
-
 	#/apple						atime=off,exec=off,setuid=off,mountpoint=/apple
-	#/git						atime=off,exec=off,setuid=off,mountpoint=/git
+	#/git							atime=off,exec=off,setuid=off,mountpoint=/git
 	#/media						atime=off,exec=off,setuid=off,mountpoint=/media
 	/distro						atime=off,exec=off,setuid=off,mountpoint=/server/tftp/distro
-	/distfiles 					atime=off,exec=off,setuid=off,mountpoint=/usr/ports/distfiles
-
-
+	/distfiles 				atime=off,exec=off,setuid=off,mountpoint=/usr/ports/distfiles
 	# Custom /server folder
 	/server						canmount=off,mountpoint=/server
-	/server/ezjail				atime=off,setuid=off,mountpoint=/usr/local/etc/ezjail
+	/server/ezjail		atime=off,setuid=off,mountpoint=/usr/local/etc/ezjail
 "
-
 SIZES="3725 3614 2794 2683 1850 1739 931 820"  # Preferred descending order in GB
-MNT=""
-
 hdd-serial() {
-	DISK=${1}
 	if [ ${#} -gt 0 ]; then
-		/usr/sbin/diskinfo -v ${DISK}
-		/sbin/camcontrol identify ${DISK} || /sbin/camcontrol inquiry ${DISK}
+		/usr/sbin/diskinfo -v "${1}"
+		/sbin/camcontrol identify "${1}" || /sbin/camcontrol inquiry "${1}"
 	fi
 }
-
 sizeinMB() {
-	number=`echo "${1}" | /usr/bin/sed "s/[[:alpha:]]*$//"`
-	suffix=`echo "${1}" | /usr/bin/sed "s/^[[:digit:]]*//"`
+	number=$( echo "${1}" | /usr/bin/sed "s/[[:alpha:]]*$//" )
+	suffix=$( echo "${1}" | /usr/bin/sed "s/^[[:digit:]]*//" )
 	case "$suffix" in
 		K|KB) multiplier=1; divisor=1024 ;;
 		M|MB) multiplier=1; divisor=1 ;;
@@ -59,11 +47,9 @@ sizeinMB() {
 	VAL=$(( ${number} * ${multiplier} / ${divisor} ))
 	echo $VAL
 }
-
 makeguid() {
 	echo "${1}$(/bin/cat /dev/random | /usr/bin/tr -cd '[:alnum:]' | /usr/bin/head -c 20)" | /usr/bin/head -c 14
 }
-
 usage() {
 	echo "Usage: $0 -d geom_provider [-d geom_provider ...] [-r mirror|raidz{1,2,3}] [-p zfs_pool_name] [-V zfs_pool_version] [-s swap_partition_size] [-E] [-n] [-c]"
 	echo ; echo "Example:"
@@ -71,7 +57,6 @@ usage() {
 	echo "Or if you want swap added too:"
 	echo "  $0 -d ada0 -d ada1 -d ada2 -d ada3 -r mirror -s 10G -E -n -c"
 }
-
 while getopts d:r:p:s:V:cENn o; do
 	case "$o" in
 		d) DEVS="$DEVS ${OPTARG##/dev/}" ;;
@@ -83,133 +68,102 @@ while getopts d:r:p:s:V:cENn o; do
 		n) HEADLESS=1; NOATIME=1 ;;
 		N) NOINSTALL=1 ;;
 		c) LZJB=1 ;;
-		[?]) usage; exit 1;;
-esac
+		[?]) usage; exit 1 ;;
+	esac
 done
-
-if ! `/sbin/kldstat -m zfs >/dev/null 2>/dev/null`; then
+if ! /sbin/kldstat -m zfs >/dev/null 2>/dev/null ; then
 	/sbin/kldload zfs >/dev/null 2>/dev/null
 fi
-
-ZFS_VERSION=`/sbin/sysctl -n vfs.zfs.version.spa 2>/dev/null`
-
+ZFS_VERSION=$( /sbin/sysctl -n vfs.zfs.version.spa 2>/dev/null )
 if [ -z "$ZFS_VERSION" ]; then
-	echo "Error: failed to load ZFS module"
-	exit 1
+	echo "Error: failed to load ZFS module" ; exit 1
 elif [ "$ZFS_VERSION" -lt "13" ]; then
-	echo "Error: ZFS module too old, version 13 or higher required"
-	exit 1
+	echo "Error: ZFS module too old, version 13 or higher required" ; exit 1
 fi
-
 if [ -z "$DEVS" ]; then
-	usage
-	exit 1
+	usage ; exit 1
 fi
-
-if [ -z "$POOL" ]; then
-	POOL=data
-fi
-
+test -z "$POOL" && POOL=data
 if [ -z "$VERSION" ]; then
-	VERSION=${ZFS_VERSION}
+	VERSION="${ZFS_VERSION}"
 elif [ "$VERSION" -gt "$ZFS_VERSION" ]; then
-	echo "Error: invalid ZFS pool version (maximum: $ZFS_VERSION)"
-	exit 1
+	echo "Error: invalid ZFS pool version (maximum: $ZFS_VERSION)" ; exit 1
 fi
-
 if [ "$VERSION" = "5000" ]; then
 	VERSION=
 else
 	VERSION="-o version=${VERSION}"
 fi
-
 if [ -z "${NOINSTALL}" ]; then
-
-	if /sbin/zpool list $POOL > /dev/null 2> /dev/null; then
-		echo Error: ZFS pool \"$POOL\" already exists
-		echo Please choose another pool name or rename/destroy the existing pool.
+	if /sbin/zpool list $POOL > /dev/null 2> /dev/null ; then
+		echo "Error: ZFS pool already exists: $POOL"
+		echo "Please choose another pool name or rename/destroy the existing pool."
 		exit 1
 	fi
-
-	EXPOOLS=`/sbin/zpool import | /usr/bin/grep pool: | /usr/bin/awk '{ print $2 }'`
-
+	EXPOOLS=$( /sbin/zpool import | /usr/bin/grep "pool:" | /usr/bin/awk '{ print $2 }' )
 	if [ -n "${EXPOOLS}" ]; then
 		for P in ${EXPOOLS}; do
 			if [ "$P" = "$POOL" ]; then
-				echo Error: An exported ZFS pool \"$POOL\" already exists
-				echo Please choose another pool name or rename/destroy the exported pool.
+				echo "Error: An exported ZFS pool already exists: $POOL"
+				echo "Please choose another pool name or rename/destroy the exported pool."
 				exit 1
 			fi
 		done
 	fi
 fi
-
-COUNT=`echo ${DEVS} | /usr/bin/wc -w | /usr/bin/awk '{ print $1 }'`
+COUNT=$( echo "${DEVS}" | /usr/bin/wc -w | /usr/bin/awk '{ print $1 }' )
 if [ "$COUNT" -lt "3" -a "$RAID" = "raidz" ]; then
-	echo "Error: raidz needs at least three devices (-d switch)"
-	exit 1
+	echo "Error: raidz needs at least three devices (-d switch)" ; exit 1
 elif [ "$COUNT" -lt "4" -a "$RAID" = "raidz2" ]; then
-	echo "Error: raidz needs at least four devices (-d switch)"
-	exit 1
+	echo "Error: raidz needs at least four devices (-d switch)" ; exit 1
 elif [ "$COUNT" -lt "5" -a "$RAID" = "raidz3" ]; then
-	echo "Error: raidz needs at least five devices (-d switch)"
-	exit 1
+	echo "Error: raidz needs at least five devices (-d switch)" ; exit 1
 elif [ "$COUNT" = "1" -a "$RAID" = "mirror" ]; then
-	echo "Error: mirror needs at least two devices (-d switch)"
-	exit 1
+	echo "Error: mirror needs at least two devices (-d switch)" ; exit 1
 elif [ "$COUNT" = "2" -a "$RAID" != "mirror" ]; then
 	echo "Notice: two drives selected, automatically choosing mirror mode"
 	RAID="mirror"
 elif [ "$COUNT" -gt "2" -a "$RAID" != "mirror" -a "$RAID" != "raidz" -a "$RAID" != "raidz2" -a "$RAID" != "raidz3" ]; then
-	echo "Error: please choose raid mode with the -r switch (mirror or raidz{1,2,3})"
-	exit 1
+	echo "Error: please choose raid mode with the -r switch (mirror or raidz{1,2,3})" ; exit 1
 fi
-
 for DEV in ${DEVS}; do
-	if ! /sbin/gpart show $DEV > /dev/null 2> /dev/null; then
+	if [ ! -c "/dev/${DEV}" ]; then
+		echo "Error: /dev/${DEV} is not a block device" ; exit 1
+	fi
+	if ! /sbin/gpart show $DEV > /dev/null 2> /dev/null ; then
 		echo -n "Creating GUID partitions on ${DEV} ..."
-		if ! /sbin/gpart create -s GPT /dev/${DEV} > /dev/null; then
-			echo " error"
-			exit 1
+		if ! /sbin/gpart create -s GPT /dev/${DEV} > /dev/null ; then
+			echo " error" ; exit 1
 		fi
 		/bin/sleep 1
 	fi
-	if ! [ -c "/dev/${DEV}" ]; then
-		echo "Error: /dev/${DEV} is not a block device"
-		exit 1
-	fi
 done
-
-SLICE=""
-SWAPSLICE="p1"
-DELIM="gptid"
-PDELIM="label"
-GELISECTOR="4096"
-ALIGN4="-a 4k"
-
+test -z "$MNT" \
+&& MNT=""
+	SLICE=""
+	SWAPSLICE="p1"
+	DELIM="label"
+	GELISECTOR="4096"
+	ALIGN4="-a 4k"
 if [ "${ALIGN4K}" = "1" ]; then
 	GELISECTOR="4096"
 	ALIGN4="-a 4k"
 fi
-
 if [ "${NOALIGN4K}" = "1" ]; then
 	GELISECTOR="512"
 	ALIGN4=""
 fi
-
 # Create GPT
-
 for DEV in ${DEVS}; do
-#part swap
+	# part swap
 	if [ -n "${SWAP}" ]; then
 		if [ "${MBR}" != "1" ]; then
-			if ! /sbin/gpart add -t freebsd-swap ${ALIGN4} -s "${SWAP}" ${DEV}${SLICE} > /dev/null; then
-				echo " error swap"
-				exit 1
+			if ! /sbin/gpart add -t freebsd-swap ${ALIGN4} -s "${SWAP}" "${DEV}${SLICE}" > /dev/null ; then
+				echo " error swap" ; exit 1
 			fi
-			LASTADDED=`/sbin/gpart show -p ${DEV}${SLICE} | /usr/bin/grep freebsd | /usr/bin/awk '{ print $3 }' | /usr/bin/tail -1`
-			/bin/dd if=/dev/zero of=/dev/${LASTADDED} bs=512 count=560 > /dev/null 2> /dev/null
-			/sbin/zpool labelclear -f /dev/${LASTADDED} > /dev/null 2> /dev/null
+			LASTADDED=$( /sbin/gpart show -p "${DEV}${SLICE}" | /usr/bin/grep freebsd | /usr/bin/awk '{ print $3 }' | /usr/bin/tail -1 )
+			/bin/dd if=/dev/zero of="/dev/${LASTADDED}" bs=512 count=560 > /dev/null 2> /dev/null
+			/sbin/zpool labelclear -f "/dev/${LASTADDED}" > /dev/null 2> /dev/null
 		fi
 	fi
 	PARTCREATED=0
@@ -219,9 +173,9 @@ for DEV in ${DEVS}; do
 				if /sbin/gpart add -t freebsd-zfs ${ALIGN4} -s ${GSIZE}G ${DEV}${SLICE} > /dev/null 2> /dev/null ; then
 					echo "  success adding partition sized ${GSIZE}G at ${DEV}"
 					PARTCREATED=1
-					LASTADDED=`/sbin/gpart show -p ${DEV}${SLICE} | /usr/bin/grep freebsd | /usr/bin/awk '{ print $3 }' | /usr/bin/tail -1`
-					/bin/dd if=/dev/zero of=/dev/${LASTADDED} bs=512 count=560 > /dev/null 2> /dev/null
-					/sbin/zpool labelclear -f /dev/${LASTADDED} > /dev/null 2> /dev/null
+					LASTADDED=$( /sbin/gpart show -p "${DEV}${SLICE}" | /usr/bin/grep freebsd | /usr/bin/awk '{ print $3 }' | /usr/bin/tail -1 )
+					/bin/dd if=/dev/zero of="/dev/${LASTADDED}" bs=512 count=560 > /dev/null 2> /dev/null
+					/sbin/zpool labelclear -f "/dev/${LASTADDED}" > /dev/null 2> /dev/null
 					ZFSLABEL="${LASTADDED}"
 				else
 					GSIZE=$(( GSIZE - 1 ))
@@ -234,133 +188,118 @@ for DEV in ${DEVS}; do
 		done
 	done
 	[ "${PARTCREATED}" != "1" ] && exit 1
-	MAKEGUID=`makeguid ${POOL}`
-	if ! /sbin/glabel label ${MAKEGUID} /dev/${ZFSLABEL} > /dev/null; then
-		echo " error zfsslice"
-		exit 1
+	MAKEGUID=$( makeguid "${POOL}" )
+	if ! /sbin/glabel label "${MAKEGUID}" "/dev/${ZFSLABEL}" > /dev/null 2> /dev/null ; then
+		echo " error zfsslice" ; exit 1
 	fi
-	/sbin/zpool labelclear -f /dev/label/${MAKEGUID}
+	/bin/dd if=/dev/zero of="/dev/label/${MAKEGUID}" bs=512 count=560 > /dev/null 2> /dev/null
+	/sbin/zpool labelclear -f "/dev/label/${MAKEGUID}"
+	/sbin/gpart show "${DEV}${SLICE}"
 done
 /bin/sleep 1
 for DEV in ${DEVS}; do
 	if [ -n "${SWAP}" ]; then
 		# Detect swap part here because we dd above
-		SWAPPARTUUID=`/sbin/glabel list ${DEV}${SWAPSLICE} | /usr/bin/grep ${DELIM} | /usr/bin/awk '{ print $3 }'`
-		if [ -z "${SWAPPARTUUID}" ]; then
-			echo " error determining swap partition"
-		fi
+		SWAPPARTUUID="${DEV}${SWAPSLICE}"
+		test -z "${SWAPPARTUUID}" && echo " error determining swap partition"
 		FSWAP="${FSWAP} ${SWAPPARTUUID}"
 	fi
 done
-
 if [ -z "${NOINSTALL}" ]; then
 	# Create mirrored swap, FSWAP is the list of swap part.
 	if [ -n "${FSWAP}" ]; then
 		/sbin/gmirror load > /dev/null 2> /dev/null
 		/sbin/gmirror label -b round-robin swap ${FSWAP}
-		#echo "/dev/mirror/swap.eli	none		swap	sw,aalgo=HMAC/SHA256	0	0" >> /etc/fstab
-		echo "/dev/mirror/swap.eli	none		swap	sw						0	0" >> /etc/fstab
+	 #echo "/dev/mirror/swap.eli	none	swap	sw,aalgo=HMAC/SHA256	0	0" >> /etc/fstab
+		if [ "$MFSBSD" != "1" ]; then
+			echo "/dev/mirror/swap.eli	none	swap	sw	0	0" >> /etc/fstab
+		fi
 		/sbin/swapon /dev/mirror/swap.eli
 	fi
 fi
-
+# Create zpool and zfs
 for DEV in ${DEVS}; do
-	DISKSERIAL=`hdd-serial ${DEV} | /usr/bin/grep -i "serial number" | /usr/bin/awk '{ print $NF }'`
-	PART=`/sbin/gpart show -p ${DEV}${SLICE} | /usr/bin/grep freebsd-zfs | /usr/bin/awk '{ print $3 }' | /usr/bin/tail -1`
+	DISKSERIAL=$( hdd-serial "${DEV}" | /usr/bin/grep -i "serial number" | /usr/bin/awk '{ print $NF }' )
+	PART=$( /sbin/gpart show -p "${DEV}${SLICE}" | /usr/bin/grep freebsd-zfs | /usr/bin/awk '{ print $3 }' | /usr/bin/tail -1 )
 	if [ -z "${PART}" ]; then
-		echo Error: freebsd-zfs partition not found on /dev/$DEV
-		exit 1
+		echo "Error: freebsd-zfs partition not found on /dev/$DEV" ; exit 1
 	fi
-	PARTUUID=`/sbin/glabel list ${PART} | /usr/bin/grep ${PDELIM} | /usr/bin/awk '{ print $3 }'`
+	PARTUUID=$( /sbin/glabel list "${PART}" | /usr/bin/grep "${DELIM}" | /usr/bin/awk '{ print $3 }' )
 	PARTS="${PARTS} ${PARTUUID}"
 	if [ "${GELI}" = "1" ]; then
-		/usr/bin/install -d -m 700	/bootdir/boot/keys > /dev/null 2> /dev/null
-		/sbin/mount | /usr/bin/grep "/bootdir" || exit 1
-
+		/usr/bin/install -d -m 700 "${BOOTDIR}/boot/keys"
+		/sbin/mount | /usr/bin/grep \
+		"/bootdir" || exit 1
 		##### Generate an alphanumeric key
 		umask 077
-		TMPKEY="/bootdir/boot/keys/`/bin/hostname -s`.${DISKSERIAL}.${PARTUUID##*/}"
-		if [ -e /bootdir/boot/keys/bootpkg ]; then
-			TMPKEY="/bootdir/boot/keys/bootpkg/`/bin/hostname -s`.${DISKSERIAL}.${PARTUUID##*/}"
-		fi
-		/bin/dd if=/dev/random of=${TMPKEY} bs=128k count=1
+		TMPKEY="${BOOTDIR}/boot/keys/`/bin/hostname -s`.${DISKSERIAL}.${PARTUUID##*/}"
+		test -d "${BOOTDIR}/boot/keys/bootpkg" \
+		&& TMPKEY="${BOOTDIR}/boot/keys/bootpkg/`/bin/hostname -s`.${DISKSERIAL}.${PARTUUID##*/}"
+		/bin/dd if=/dev/random of="${TMPKEY}" bs=128k count=1
 		umask $RESTOREMASK
-		/bin/chmod go-rwx /bootdir/boot/keys
-		/bin/chmod go-rwx ${TMPKEY}
-	fi
-	if [ "${GELI}" = "1" ]; then
+		/bin/chmod go-rwx "${BOOTDIR}/boot/keys"
+		/bin/chmod go-rwx "${TMPKEY}"
 		if [ -n "${HEADLESS}" ]; then
 			##### PASSWORDLESS
-			/sbin/geli init -b -P -K ${TMPKEY} -e AES-XTS -s ${GELISECTOR} ${PARTUUID}
-			/sbin/geli attach  -p -k ${TMPKEY} ${PARTUUID}
+			/sbin/geli init -b -P -K "${TMPKEY}" -e AES-XTS -s ${GELISECTOR} "${PARTUUID}"
+			/sbin/geli attach  -p -k "${TMPKEY}" "${PARTUUID}"
 		else
 			##### PASSWORD AT CONSOLE
-			/sbin/geli init -b    -K ${TMPKEY} -e AES-XTS -s ${GELISECTOR} ${PARTUUID}
-			/sbin/geli attach     -k ${TMPKEY} ${PARTUUID}
+			/sbin/geli init -b    -K "${TMPKEY}" -e AES-XTS -s ${GELISECTOR} "${PARTUUID}"
+			/sbin/geli attach     -k "${TMPKEY}" "${PARTUUID}"
 		fi
 		EPARTS="${EPARTS} ${PARTUUID}.eli"
 		umask 077
-		SAFEPARTUUID=`echo ${PARTUUID} | /usr/bin/sed 's#/#_#'`
-		if [ ! -e /bootdir/boot/keys/bootpkg ]; then
-			/usr/sbin/sysrc -f /tmp/loader.keys geli_${SAFEPARTUUID}_keyfile0_load="YES"
-			/usr/sbin/sysrc -f /tmp/loader.keys geli_${SAFEPARTUUID}_keyfile0_type="${PARTUUID}:geli_keyfile0"
-			/usr/sbin/sysrc -f /tmp/loader.keys geli_${SAFEPARTUUID}_keyfile0_name="${TMPKEY}"
+		SAFEPARTUUID=$( echo "${PARTUUID}" | /usr/bin/sed 's#/#_#' )
+		if [ ! -d "${BOOTDIR}/boot/keys/bootpkg" ]; then
+			/usr/sbin/sysrc -f /tmp/loader.keys "geli_${SAFEPARTUUID}_keyfile0_load=YES"
+			/usr/sbin/sysrc -f /tmp/loader.keys "geli_${SAFEPARTUUID}_keyfile0_type=${PARTUUID}:geli_keyfile0"
+			/usr/sbin/sysrc -f /tmp/loader.keys "geli_${SAFEPARTUUID}_keyfile0_name=${TMPKEY}"
 		fi
 		umask $RESTOREMASK
 	fi
 done
-
-oldautomount="$( sysrc -n -f /bootdir/boot/loader.conf automount )"
-/usr/sbin/sysrc -f /bootdir/boot/loader.conf automount="${oldautomount} data"
-
-POOLPARTS=${PARTS}
+oldautomount=$( sysrc -n -f "${BOOTDIR}/boot/loader.conf" automount )
+/usr/sbin/sysrc -f "${BOOTDIR}/boot/loader.conf" automount="${oldautomount} data"
+POOLPARTS="${PARTS}"
 if [ "${GELI}" = "1" ]; then
-	POOLPARTS=${EPARTS}
-	if [ -e "/server/bin/bp" ]; then
-		if [ -x /server/bin/bp ]; then
-			/server/bin/bp umount
-		fi
-	fi
+	POOLPARTS="${EPARTS}"
+	test -x /server/bin/bp && /server/bin/bp umount
 fi
-
 if [ -z "${NOINSTALL}" ]; then
 	echo -n "Creating ZFS pool ${POOL} on ${POOLPARTS} ..."
-	if ! /sbin/zpool create -f ${VERSION} ${POOL} ${RAID} ${POOLPARTS} > /dev/null 2> /dev/null; then
-		echo " error"
-		exit 1
+	if ! /sbin/zpool create -f ${VERSION} "${POOL}" ${RAID} ${POOLPARTS} > /dev/null 2> /dev/null ; then
+		echo " error" ; exit 1
 	fi
 	echo " done"
-
+	# LZJB
 	if [ "${LZJB}" = "1" ]; then
 		echo -n "Setting default compression to lzjb for ${POOL} ..."
-		if ! /sbin/zfs set compression=lzjb ${POOL} > /dev/null 2> /dev/null; then
-			echo " error"
-			exit 1
+		if ! /sbin/zfs set compression=lzjb "${POOL}" > /dev/null 2> /dev/null ; then
+			echo " error" ; exit 1
 		fi
 		echo " done"
 	fi
-
+	# NOATIME
 	if [ "${NOATIME}" = "1" ]; then
 		echo -n "Setting default atime to off for ${POOL} ..."
-		if ! /sbin/zfs set atime=off ${POOL} > /dev/null 2> /dev/null; then
-			echo " error"
-			exit 1
+		if ! /sbin/zfs set atime=off "${POOL}" > /dev/null 2> /dev/null ; then
+			echo " error" ; exit 1
 		fi
 		echo " done"
 	fi
-
 	if [ "${POOL}" = "data" ]; then
 		DISABLEDATASETS="
 autoroot/rfs/usr/ports/distfiles
 autoroot/rfs/server/ezjail
 "
+		# Disable some datasets
 		echo "$DISABLEDATASETS" | while read dataset; do
 			# Skip blank lines and comments
 			case "$dataset" in "#"*|"") continue; esac
 			/sbin/zfs umount "$dataset"
 			/sbin/zfs set canmount=off "$dataset"
 		done
-
 		echo -n "Creating ${POOL} partitions:"
 		echo "$ZFSBOOT_DATASETS" | while read dataset options; do
 			# Skip blank lines and comments
@@ -375,38 +314,34 @@ autoroot/rfs/server/ezjail
 				oldoptions="$options"
 				f_replaceall "$options" "  " " " options
 			done
-			# Replace both commas and spaces with ` -o '
+			# Replace both commas and spaces with ' -o '
 			f_replaceall "$options" "[ ,]" " -o " options
 			# Create the dataset with desired options
 			MNTPT=
-			if ! /sbin/zfs create ${options:+-o $options} ${MNTPT} "${POOL}${dataset}" > /dev/null 2> /dev/null; then
-				echo " error"
-				exit 1
+			if ! /sbin/zfs create ${options:+-o $options} ${MNTPT} "${POOL}${dataset}" > /dev/null 2> /dev/null ; then
+				echo " error" ; exit 1
 			fi
 			echo -n " ${dataset}"
 		done
 		echo " ... done"
 	fi
-	/sbin/zfs list -r ${POOL}
+	/sbin/zfs list -r "${POOL}"
 fi
-
 	if [ "${GELI}" = "1" ]; then
-		/usr/sbin/sysrc -f ${MNT}/bootdir/boot/loader.conf geom_eli_load="YES"
+		/usr/sbin/sysrc -f "${MNT}${BOOTDIR}/boot/loader.conf" geom_eli_load="YES"
 		umask 077
-		/usr/bin/install -d -m 700	${MNT}/var/backups > /dev/null 2> /dev/null
-		/bin/cp -Rpv /var/backups/*.eli ${MNT}/var/backups/
+		/usr/bin/install -d -m 700			"${MNT}/var/backups"
+		/bin/cp -Rpv /var/backups/*.eli "${MNT}/var/backups/"
 		umask $RESTOREMASK
 	fi
-
 	if [ -n "${FSWAP}" ]; then
 		if [ "${GELI}" = "1" ]; then
 			#echo "/dev/mirror/swap.eli	none		swap	sw,aalgo=HMAC/SHA256	0	0" >> ${MNT}/etc/fstab
-			echo "/dev/mirror/swap.eli	none		swap	sw						0	0" >> ${MNT}/etc/fstab
+			echo "/dev/mirror/swap.eli	none	swap	sw	0	0" >> "${MNT}/etc/fstab"
 		else
-			echo "/dev/mirror/swap		none		swap	sw						0	0" >> ${MNT}/etc/fstab
+			echo "/dev/mirror/swap			none	swap	sw	0	0" >> "${MNT}/etc/fstab"
 		fi
 	fi
-
 if [ "${NOINSTALL}" = "1" ]; then
 	if [ -n "${FSWAP}" ]; then
 		/bin/cat <<EOF
@@ -428,11 +363,10 @@ EOF
 		echo "	/sbin/zpool attach ${POOL} existing_device.eli ${a}"
 	done
 fi
-
 /bin/cat <<EOF
 YOU MAY WANT TO COPY KEYS TO BOOTPKG:
-	bp mount && cp -an /bootdir/boot/keys/`hostname -s`*${POOL}*  /bootdir/boot/keys/bootpkg/
-	cat /tmp/loader.keys >> /bootdir/boot/keys/bootpkg/loader.keys
+	bp mount && cp -an ${BOOTDIR}/boot/keys/`hostname -s`*${POOL}*  ${BOOTDIR}/boot/keys/bootpkg/
+	cat /tmp/loader.keys >> ${BOOTDIR}/boot/keys/bootpkg/loader.keys
 !!!!!!!!!!
 ! IF YOU USE BOOTPKG, copy /server/root/bootpkg.gz to a safe place
 !!!!!!!!!!
diff --git a/keys/all/server/bin/zquickinstall b/keys/all/server/bin/zquickinstall
--- a/keys/all/server/bin/zquickinstall
+++ b/keys/all/server/bin/zquickinstall
@@ -13,6 +13,9 @@ usage() {
 uri="http://${server}:${port}"
 mfsbsdiso="${uri}/mfsbsd/mfsbsd.iso"
 MFSBSD=1; PASSMFSBSD="-M -c" ;
+DETECTEDDRIVES=""
+ISMIRROR=""
+DRIVECOUNT=0
 
 unset FORCE
 
@@ -28,81 +31,117 @@ while getopts d:u:t:T:iM o; do
 	esac
 done
 
-DETECTEDDRIVES=""
-ISMIRROR=""
-DRIVECOUNT=0
-
 doInstall() {
-	DRIVELIST="`/sbin/sysctl -n kern.disks`"
-	TRIMDEVS="`echo $DEVS | /usr/bin/tr -d ' '`"
-	if [ -n "$TRIMDEVS" ]; then
-		DRIVELIST="$DEVS"
-	fi
-	for drive in ${DRIVELIST} ; do
-		if ! echo "${drive##*/}" | /usr/bin/egrep "cd[0-9]" > /dev/null 2> /dev/null ; then
-			echo -n "${drive##*/}... "
-			if /sbin/gpart show "${drive##*/}" >/dev/null 2>/dev/null ; then
-				echo "Drives not empty, use destroygeom"
-				exit 1
-			else
-				DETECTEDDRIVES="${DETECTEDDRIVES}-d ${drive##*/} "
-				DRIVECOUNT=$(( DRIVECOUNT + 1 ))
-			fi
-		fi
-	done
-	if [ $DRIVECOUNT -gt 1 ]; then
-		ISMIRROR="-r mirror"
-	fi
 
-	[ "$FORCE" = "1" ] && /server/bin/destroygeom ${DETECTEDDRIVES}
+	DRIVELIST="`/sbin/sysctl -n kern.disks`"
+
+	TRIMDEVS="`echo $DEVS | /usr/bin/tr -d ' '`"
+
+	test -n "$TRIMDEVS" && DRIVELIST="$DEVS"
+
+	for drive in ${DRIVELIST} ; do
+
+		if ! echo "${drive##*/}" | /usr/bin/egrep "cd[0-9]" > /dev/null 2> /dev/null ; then
+
+			echo -n "${drive##*/}... "
+
+			if /sbin/gpart show "${drive##*/}" >/dev/null 2>/dev/null ; then
+				echo "Drives not empty, use destroygeom" ; exit 1
+			fi
+
+			DETECTEDDRIVES="${DETECTEDDRIVES}-d ${drive##*/} "
+
+			DRIVECOUNT=$(( DRIVECOUNT + 1 ))
+
+		fi
+
+	done
+
+	test $DRIVECOUNT -gt 1 && ISMIRROR="-r mirror"
+
+	test "$FORCE" = "1" && /server/bin/destroygeom ${DETECTEDDRIVES}
 
 	if echo | /usr/bin/nc -w 3 -v ${server} ${port} ; then
+
 		#/usr/bin/fetch "${mfsbsdiso}"
+		echo
+
 	fi
 
 	if [ -f mfsbsd.iso ]; then
+
 		/server/bin/mount_iso mfsbsd.iso /media \
-			&& cd /media \
-			&& /server/bin/bs v \
-			&& /bin/rm -r ~/.gnupg/
+		&& cd /media \
+		&& /server/bin/bs v \
+		&& /bin/rm -r ~/.gnupg/
+
 	else
+
 		echo "Can't fetch ${mfsbsdiso}"
-		/sbin/mount_cd9660 -o ro /dev/cd0 /media || \
-			/sbin/mount -o ro /dev/da0a /media
-		if [ -e "/media/NOX-${RELEASE}-${ARCH}.tar" ]; then
-			ARCHIVE="/media/NOX-${RELEASE}-${ARCH}.tar"
-		fi
+
+		/sbin/mount_cd9660 -o ro /dev/cd0 /media \
+		|| /sbin/mount -o ro /dev/da0a /media
+
+		test -e "/media/NOX-${RELEASE}-${ARCH}.tar" \
+		&& ARCHIVE="/media/NOX-${RELEASE}-${ARCH}.tar"
+
 	fi
 
 	if [ -z "$URL" ]; then
+
 		if [ -d /media/${RELEASE}-${ARCH}/ ]; then
+
 			disturl="-u /media/${RELEASE}-${ARCH}"
+
 		else
+
 			disturl="-u ${uri}/${RELEASE}-${ARCH}"
+
 		fi
+
 	fi
 
 	if [ "$MFSBSD" = "1" ]; then
+
 		if [ -z "$ARCHIVE" ]; then
+
 			disturl="-T http://${server}:${port}/mfsbsd/${RELEASE}-${ARCH}/NOX-${RELEASE}-${ARCH}.tar"
+
 		else
+
 			if [ -z "$FETCH" ]; then
+
 				disturl="-t ${ARCHIVE}"
+
 				if [ ! -e "$ARCHIVE" ]; then
-					echo "Missing file: ${ARCHIVE}"
-					exit 1
+					echo "Missing file: ${ARCHIVE}" ; exit 1
 				fi
+
 			else
+
 				disturl="-T ${FETCH}"
+
 			fi
+
 		fi
+
 	fi
 
 	cat <<EOF
 Trying:
-    /server/bin/zfsinstall ${DETECTEDDRIVES} ${ISMIRROR} ${disturl} ${PASSMFSBSD} -p autoroot -s 10G -z 30G -b 1G -E -n
+	/server/bin/zfsinstall ${DETECTEDDRIVES} ${ISMIRROR} ${disturl} ${PASSMFSBSD} -p autoroot -s 10G -z 30G -b 1G -E -n
 EOF
 	/server/bin/zfsinstall ${DETECTEDDRIVES} ${ISMIRROR} ${disturl} ${PASSMFSBSD} -p autoroot -s 10G -z 30G -b 1G -E -n || exit 1
+
+	if /bin/ls -1 /media/*.csv > /dev/null 2> /dev/null ; then
+
+		for i in $( /bin/ls -1 /media/*.csv ); do
+
+			/bin/cp -av "${i}" /mnt/bootdir/ || exit 1
+
+		done
+
+	fi
 
 	cat <<EOF
 To change root passwd, do:
@@ -115,12 +154,4 @@ EOF
 
 }
 
-#echo " @@ WARNING @@"
-#echo "This will wipe all drives. Are you sure? (y/n) "
-#read REPLY
-#echo
-#case "$REPLY" in
-#	"Y"|"y")
-		doInstall || exit 1
-#		;;
-#esac
+doInstall || exit 1
