qemu imporvement

diff --git a/keys/all/server/bin/qemuvnclivecd b/keys/all/server/bin/qemuvnclivecd
--- a/keys/all/server/bin/qemuvnclivecd
+++ b/keys/all/server/bin/qemuvnclivecd
@@ -1,12 +1,25 @@
 #!/bin/sh
 # Copyright (c) 2014 John Ko
 
-ISO="$1"
+# Test for execute bit on file, or exit 1
+testforx (){
+	[ $# -lt 1 ] && echo "Usage: `basename $0` file" && exit 1
+	if [ ! -x "$1" ]; then
+		echo "Error: $1 not found or executable"; exit 1
+	fi
+}
 
-if [ "x" = "x${ISO}" ]; then
+if [ ! -x /usr/local/bin/qemu-system-x86_64 ]; then
+	/usr/local/sbin/pkg-static install -y qemu-devel > /dev/null 2> /dev/null
+fi
+
+if [ "x" = "x${1}" ]; then
 	echo "Usage: $0 /path/to/iso"
 	exit 1
 fi
+
+testforx /server/bin/net-nic
+testforx /usr/local/bin/qemu-system-x86_64
 
 /sbin/ifconfig bridge0 addm tap0 addm `/server/bin/net-nic` up
 
@@ -17,7 +30,10 @@ change vnc password
 EOF
 
 /usr/local/bin/qemu-system-x86_64 \
-	-net nic,model=e1000 -net tap \
+	-net nic,model=e1000 \
+	-net tap \
+	-usb \
+	-usbdevice tablet \
 	-vnc 0.0.0.0:0,password -monitor stdio \
 	-m 2G \
-	-cdrom ${ISO}
+	-cdrom ${1}
