fail if nginx still not installed

diff --git a/keys/all/server/bin/startnginx b/keys/all/server/bin/startnginx
--- a/keys/all/server/bin/startnginx
+++ b/keys/all/server/bin/startnginx
@@ -1,7 +1,7 @@
 #!/bin/sh
 # Copyright (c) 2014 John Ko
 
-/server/bin/startconfig nginx
+test -x /server/bin/startconfig && /server/bin/startconfig nginx
 
 /usr/sbin/sysrc -f /etc/rc.conf nginx_enable="YES"
 /usr/sbin/sysrc -f /etc/rc.conf nginx_profiles=""
@@ -12,6 +12,10 @@
 
 if [ ! -f "/usr/local/etc/rc.d/nginx" ]; then
 	/usr/local/sbin/pkg-static install -y nginx
+fi
+
+if [ ! -f "/usr/local/etc/rc.d/nginx" ]; then
+	echo "Error nginx not installed." ; exit 1
 fi
 
 /usr/bin/install -m 644 /usr/local/etc/nginx/mime.types /server/nginx/mime.types
