reduce delay if pkg repo is unreachable

diff --git a/keys/all/server/bin/startezjail b/keys/all/server/bin/startezjail
--- a/keys/all/server/bin/startezjail
+++ b/keys/all/server/bin/startezjail
@@ -1,10 +1,17 @@
 #!/bin/sh
 # Copyright (c) 2014 John Ko
 
+# Install ezjail if ezjail-admin doesn't exist and we have network
+if [ ! -e /usr/local/bin/ezjail-admin ]; then
+	/sbin/ifconfig | /usr/bin/grep status | /usr/bin/grep -v "no carrier" \
+	| /usr/bin/grep . > /dev/null 2> /dev/null \
+	&& /usr/local/sbin/pkg-static install -y ezjail
+fi
 
-# Install ezjail if ezjail-admin doesn't exist
-test -e /usr/local/bin/ezjail-admin \
-|| /usr/local/sbin/pkg-static install -y ezjail
+# Exit if ezjail still doesn't exist
+if [ ! -e /usr/local/bin/ezjail-admin ]; then
+	echo "Error: ezjail-admin not found"; exit 1
+fi
 
 # Test for net-ipreal as we use it below
 if [ ! -x /server/bin/net-ipreal ] ; then
diff --git a/keys/all/server/bin/startgui b/keys/all/server/bin/startgui
--- a/keys/all/server/bin/startgui
+++ b/keys/all/server/bin/startgui
@@ -10,9 +10,20 @@ xfce4-netload-plugin xfce4-notification-daemon xfce4-print xfce4-quicklauncher-p
 xfce4-screenshooter-plugin xfce4-systemload-plugin xfce4-taskmanager xfce4-terminal \
 xfce4-timer-plugin xfce4-volumed xfce4-weather-plugin xfce4-wm-themes xfce4-wmdock-plugin"
 
-for i in ${PACKAGES} ; do
-	/usr/local/sbin/pkg-static install -y ${i}
-done
+# Install ezjail if ezjail-admin doesn't exist and we have network
+if [ ! -e /usr/local/bin/Xorg ]; then
+	if /sbin/ifconfig | /usr/bin/grep status | /usr/bin/grep -v "no carrier" \
+	| /usr/bin/grep . > /dev/null 2> /dev/null ; then
+		for i in ${PACKAGES} ; do
+			/usr/local/sbin/pkg-static install -y ${i}
+		done
+	fi
+fi
+
+# Exit if Xorg still doesn't exist
+if [ ! -e /usr/local/bin/Xorg ]; then
+	echo "Error: Xorg not found"; exit 1
+fi
 
 SERVICES="dbus hald slim"
 
diff --git a/keys/mfsbsdonly/etc/rc.d/jautopkg b/keys/mfsbsdonly/etc/rc.d/jautopkg
--- a/keys/mfsbsdonly/etc/rc.d/jautopkg
+++ b/keys/mfsbsdonly/etc/rc.d/jautopkg
@@ -30,9 +30,12 @@ jautopkg_start()
 	if /usr/bin/fetch -o /dev/null -T 10 "${REPOURL}/digests.txz" ; then
 		TRIMLIST="`echo $autopkg | /usr/bin/tr -d ' '`"
 		if [ -n "${TRIMLIST}" ]; then
-			for i in ${autopkg} ; do
-				/usr/local/sbin/pkg-static install -y $i || echo "ERROR: pkg install $i"
-			done
+			if /sbin/ifconfig | /usr/bin/grep status | /usr/bin/grep -v "no carrier" \
+			| /usr/bin/grep . > /dev/null 2> /dev/null ; then
+				for i in ${autopkg} ; do
+					/usr/local/sbin/pkg-static install -y $i || echo "ERROR: pkg install $i"
+				done
+			fi
 			if ! /usr/local/sbin/pkg info | /usr/bin/grep 'rsync' > /dev/null 2> /dev/null; then
 				local trylocal="YES"
 			fi
