RELEASE distro in var/backups

diff --git a/keys/all/server/bin/zfsinstall b/keys/all/server/bin/zfsinstall
--- a/keys/all/server/bin/zfsinstall
+++ b/keys/all/server/bin/zfsinstall
@@ -852,11 +852,15 @@ if [ -z "${NOINSTALL}" ]; then
 	echo -n "Extracting FreeBSD distribution ..."
 	for file in ${EXTRACT_FILES}; do
 		if [ "$MFSBSD" = "1" ]; then
-			if ! /usr/bin/tar -C ${MNT}/bootdir --exclude=boot -x -f ${file} > /dev/null 2> /dev/null; then
+			if ! /usr/bin/tar -C ${MNT}/bootdir --exclude=boot --exclude=${RELEASE}-${ARCH} -x -f ${file} > /dev/null 2> /dev/null; then
 				echo " error"
 				exit 1
 			fi
 			if ! /usr/bin/tar -C ${MNT} --include=boot -x -f ${file} > /dev/null 2> /dev/null; then
+				echo " error"
+				exit 1
+			fi
+			if ! /usr/bin/tar -C ${MNT}/var/backups --include=${RELEASE}-${ARCH} -x -f ${file} > /dev/null 2> /dev/null; then
 				echo " error"
 				exit 1
 			fi
